"""Reverse-translation tables: amino acid -> pattern of matching codons.

Tables 1-23 are transcribed from the %p2c hashes of pal2nal.v14.pl; tables
24-37 were added in v15 and are derived from the NCBI and Wikipedia sources
described under PROVENANCE below. A pattern matches a codon rather than the
other way round, which is
how pal2nal locates the codon for an aligned residue; the alternatives
spell out IUPAC ambiguity (``U|T`` for RNA input, ``A|G|R`` for purines,
``U|T|C|Y`` for pyrimidines) and ``.`` stands for a fully degenerate third
position, so ambiguity codes in the input DNA still match.

Two keys are not amino acids:

``B``
    the initiation codons of the table. pal2nal v14 treats the initiating
    Met separately from internal Met, which is what lets a gene starting
    at GTG or TTG be recognised.
``X``
    any codon.

``*`` and ``_`` are both accepted for an in-frame stop.

Tables 3, 10, 11 and 13 differ deliberately from pal2nal v14; see
MODIFIED_TABLES.

Every table here is checked against NCBI's own ``gc.prt`` on all 64 codons
by ``tests/test_codontables.py``, which is the check that identified the
table 10 defect in the first place.
"""

from __future__ import annotations

import re
from typing import Final

#: Genetic codes pal2nal accepts, in the order the web form lists them.
SUPPORTED: Final[tuple[int, ...]] = (
    1, 2, 3, 4, 5, 6, 9, 10, 11, 12, 13, 14, 15, 16, 21, 22, 23,
    24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
    34, 35, 36, 37,
)

#: NCBI name of each supported genetic code.
NAMES: Final[dict[int, str]] = {
     1: "Universal code",
     2: "Vertebrate mitochondrial code",
     3: "Yeast mitochondrial code",
     4: "Mold, Protozoan and Coelenterate mitochondrial code, and Mycoplasma/Spiroplasma code",
     5: "Invertebrate mitochondrial code",
     6: "Ciliate, Dasycladacean and Hexamita nuclear code",
     9: "Echinoderm and Flatworm mitochondrial code",
    10: "Euplotid nuclear code",
    11: "Bacterial, archaeal and plant plastid code",
    12: "Alternative yeast nuclear code",
    13: "Ascidian mitochondrial code",
    14: "Alternative flatworm mitochondrial code",
    15: "Blepharisma nuclear code",
    16: "Chlorophycean mitochondrial code",
    21: "Trematode mitochondrial code",
    22: "Scenedesmus obliquus mitochondrial code",
    23: "Thraustochytrium mitochondrial code",
    24: "Rhabdopleuridae mitochondrial code",
    25: "Candidate division SR1 and Gracilibacteria code",
    26: "Pachysolen tannophilus nuclear code",
    27: "Karyorelict nuclear code",
    28: "Condylostoma nuclear code",
    29: "Mesodinium nuclear code",
    30: "Peritrich nuclear code",
    31: "Blastocrithidia nuclear code",
    32: "Balanophoraceae plastid code",
    33: "Cephalodiscidae mitochondrial code",
    34: "Enterosoma code (not an NCBI table)",
    35: "Peptacetobacter code (not an NCBI table)",
    36: "Anaerococcus and Onthovivens code (not an NCBI table)",
    37: "Absconditabacterales code (not an NCBI table)",
}

#: Where this module knowingly departs from pal2nal.v14.pl.
MODIFIED_TABLES: Final[dict[int, str]] = {
    10: (
        "pal2nal v14 never implemented the Euplotid nuclear code: TGA was "
        "left in the stop pattern and missing from Cys, making -codontable 10 "
        "behave exactly like table 1. TGA now codes for Cys, as NCBI defines it."
    ),
    3: (
        "v14 does not accept GTG as an initiation codon for the yeast "
        "mitochondrial code; NCBI added it in gc.prt 4.4, after v14 was "
        "written. GTG is now accepted."
    ),
    11: (
        "v14 accepts only ATG, CTG, GTG and TTG as initiation codons for the "
        "bacterial code, omitting ATT, ATC and ATA with no NCBI changelog "
        "entry to explain it. All seven NCBI lists are now accepted."
    ),
    13: (
        "v14 does not accept ATA as an initiation codon for the ascidian "
        "mitochondrial code; NCBI added it in gc.prt 4.0, after v14 was "
        "written. ATA is now accepted."
    ),
}

#: Where each table came from. Tables 1-23 are v14's; the rest are new in v15.
#:
#: ``ncbi``
#:     Derived from NCBI's ``gc.prt`` (vendored as ``tests/data/ncbi_gc.prt``):
#:     the amino acid of each codon from ``ncbieaa``, the initiation codons
#:     from ``sncbieaa``. A codon marked ``*`` in *either* row is a stop, which
#:     is how the context-dependent stops of tables 27, 28 and 31 are kept —
#:     those codons match both their amino acid and ``*``.
#: ``wikipedia``
#:     The four codes found by Shulgina & Eddy (2021, eLife 10:e71402) and
#:     listed by Wikipedia's "List of genetic codes" as 34-37. NCBI has *not*
#:     adopted them and has assigned no ids past 33, so these numbers are
#:     Wikipedia's own and could collide with a future NCBI assignment.
#:     Wikipedia publishes no initiation codons for them; all four organisms
#:     are bacteria, so the bacterial code's start set (table 11) is assumed.
PROVENANCE: Final[dict[int, str]] = {
    **{t: "pal2nal.v14.pl" for t in (1, 2, 3, 4, 5, 6, 9, 10, 11, 12, 13, 14, 15, 16, 21, 22, 23)},
    **{t: "ncbi" for t in range(24, 34)},
    **{t: "wikipedia" for t in range(34, 38)},
}

#: Tables whose initiation codons are assumed rather than sourced.
ASSUMED_STARTS: Final[tuple[int, ...]] = (34, 35, 36, 37)

#: amino acid -> codon pattern, per genetic code.
P2C: Final[dict[int, dict[str, str]]] = {
    1: {
        "A":  "(GC.)",
        "B":  "((U|T|C|Y|A)(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)A(A|G|R))|((T|U)GA))",
        "_":  "(((U|T)A(A|G|R))|((T|U)GA))",
    },
    2: {
        "A":  "(GC.)",
        "B":  "((A(U|T).)|G(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)(A|G|R))",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "(CG.)",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(A|G|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)A(A|G|R))|(AG(A|G|R)))",
        "_":  "(((U|T)A(A|G|R))|(AG(A|G|R)))",
    },
    3: {
        "A":  "(GC.)",
        "B":  "((A(U|T)(A|G|R))|(G(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y))",
        "K":  "(AA(A|G|R))",
        "L":  "((U|T)(U|T)(A|G|R))",
        "M":  "(A(U|T)(A|G|R))",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "((AC.)|(C(U|T).))",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(A|G|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)A(A|G|R))",
        "_":  "((U|T)A(A|G|R))",
    },
    4: {
        "A":  "(GC.)",
        "B":  "((A(U|T).)|((U|T)(U|T)(A|G|R))|(C(U|T)G)|(G(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(A|G|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)A(A|G|R))",
        "_":  "((U|T)A(A|G|R))",
    },
    5: {
        "A":  "(GC.)",
        "B":  "((A(U|T).)|((U|T|A|G|R)(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)(A|G|R))",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "(CG.)",
        "S":  "(((U|T)C.)|(AG.))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(A|G|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)A(A|G|R))",
        "_":  "((U|T)A(A|G|R))",
    },
    6: {
        "A":  "(GC.)",
        "B":  "(A(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "((CA(A|G|R))|((U|T)A(A|G|R)))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((T|U)GA)",
        "_":  "((T|U)GA)",
    },
    9: {
        "A":  "(GC.)",
        "B":  "((A|G|R)(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AAG)",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y|A))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "(CG.)",
        "S":  "(((U|T)C.)|(AG.))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(A|G|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)A(A|G|R))",
        "_":  "((U|T)A(A|G|R))",
    },
    10: {
        "A":  "(GC.)",
        "B":  "(A(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y|A))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)A(A|G|R))",
        "_":  "((U|T)A(A|G|R))",
    },
    11: {
        "A":  "(GC.)",
        "B":  "((A(U|T).)|(C(U|T)G)|(G(U|T)G)|((U|T)(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)A(A|G|R))|((T|U)GA))",
        "_":  "(((U|T)A(A|G|R))|((T|U)GA))",
    },
    12: {
        "A":  "(GC.)",
        "B":  "((A|C)(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T)(U|T|C|Y|A))|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y))|(C(U|T)G))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)A(A|G|R))|((T|U)GA))",
        "_":  "(((U|T)A(A|G|R))|((T|U)GA))",
    },
    13: {
        "A":  "(GC.)",
        "B":  "((A(U|T)(A|G|R))|(G(U|T)G)|((U|T)(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "((GG.)|(AG(A|G|R)))",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)(A|G|R))",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "(CG.)",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(A|G|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)A(A|G|R))",
        "_":  "((U|T)A(A|G|R))",
    },
    14: {
        "A":  "(GC.)",
        "B":  "(A(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AAG)",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y|A))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "(CG.)",
        "S":  "(((U|T)C.)|(AG.))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(G|A|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y|A))",
        "*":  "((U|T)AG)",
        "_":  "((U|T)AG)",
    },
    15: {
        "A":  "(GC.)",
        "B":  "(A(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "((CA(A|G|R))|((U|T)AG))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)AA)|((T|U)GA))",
        "_":  "(((U|T)AA)|((T|U)GA))",
    },
    16: {
        "A":  "(GC.)",
        "B":  "(A(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R))|((U|T)AG))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)AA)|((T|U)GA))",
        "_":  "(((U|T)AA)|((T|U)GA))",
    },
    21: {
        "A":  "(GC.)",
        "B":  "((A|G|R)(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y))",
        "K":  "(AAG)",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)(A|G|R))",
        "N":  "(AA(U|T|C|Y|A))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "(CG.)",
        "S":  "(((U|T)C.)|(AG.))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(A|G|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)A(A|G|R))",
        "_":  "((U|T)A(A|G|R))",
    },
    22: {
        "A":  "(GC.)",
        "B":  "(A(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R))|((T|U)AG))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C(U|T|C|Y|G))|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)(C|A|G|R)A)",
        "_":  "((U|T)(C|A|G|R)A)",
    },
    23: {
        "A":  "(GC.)",
        "B":  "(((A|G|R)(U|T)G)|(A(U|T)(U|T)))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)G))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)A(A|G|R))|((T|U)GA)|((T|U)(T|U)A))",
        "_":  "(((U|T)A(A|G|R))|((T|U)GA)|((T|U)(T|U)A))",
    },
    24: {
        "A":  "(GC.)",
        "B":  "((A(U|T)G)|(C(U|T)G)|(G(U|T)G)|((U|T)(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "((AA(A|G|R))|(AGG))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "(CG.)",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y|A)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(A|G|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)A(A|G|R))",
        "_":  "((U|T)A(A|G|R))",
    },
    25: {
        "A":  "(GC.)",
        "B":  "((A(U|T)G)|(G(U|T)G)|((U|T)(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "((GG.)|((U|T)GA))",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)A(A|G|R))",
        "_":  "((U|T)A(A|G|R))",
    },
    26: {
        "A":  "((GC.)|(C(U|T)G))",
        "B":  "((A(U|T)G)|(C(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T)(U|T|C|Y|A))|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)A(A|G|R))|((U|T)GA))",
        "_":  "(((U|T)A(A|G|R))|((U|T)GA))",
    },
    27: {
        "A":  "(GC.)",
        "B":  "(A(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "((CA(A|G|R))|((U|T)A(A|G|R)))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(A|G|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)GA)",
        "_":  "((U|T)GA)",
    },
    28: {
        "A":  "(GC.)",
        "B":  "(A(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "((CA(A|G|R))|((U|T)A(A|G|R)))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(A|G|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)A(A|G|R))|((U|T)GA))",
        "_":  "(((U|T)A(A|G|R))|((U|T)GA))",
    },
    29: {
        "A":  "(GC.)",
        "B":  "(A(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A.)",
        "*":  "((U|T)GA)",
        "_":  "((U|T)GA)",
    },
    30: {
        "A":  "(GC.)",
        "B":  "(A(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "((GA(A|G|R))|((U|T)A(A|G|R)))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)GA)",
        "_":  "((U|T)GA)",
    },
    31: {
        "A":  "(GC.)",
        "B":  "(A(U|T)G)",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "((GA(A|G|R))|((U|T)A(A|G|R)))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(A|G|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)A(A|G|R))",
        "_":  "((U|T)A(A|G|R))",
    },
    32: {
        "A":  "(GC.)",
        "B":  "((A(U|T).)|(C(U|T)G)|(G(U|T)G)|((U|T)(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "(((U|T)AG)|((U|T)GG))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)AA)|((U|T)GA))",
        "_":  "(((U|T)AA)|((U|T)GA))",
    },
    33: {
        "A":  "(GC.)",
        "B":  "((A(U|T)G)|(C(U|T)G)|(G(U|T)G)|((U|T)(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "((AA(A|G|R))|(AGG))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "(CG.)",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y|A)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)G(A|G|R))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y|A))",
        "*":  "((U|T)AG)",
        "_":  "((U|T)AG)",
    },
    34: {
        "A":  "(GC.)",
        "B":  "((A(U|T).)|(C(U|T)G)|(G(U|T)G)|((U|T)(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "((AGG)|(A(U|T)G))",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG.)|(AGA))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)A(A|G|R))|((U|T)GA))",
        "_":  "(((U|T)A(A|G|R))|((U|T)GA))",
    },
    35: {
        "A":  "(GC.)",
        "B":  "((A(U|T).)|(C(U|T)G)|(G(U|T)G)|((U|T)(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "((CA(A|G|R))|(CGG))",
        "R":  "((CG(U|T|C|Y|A))|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((U|T)GG)",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)A(A|G|R))|((U|T)GA))",
        "_":  "(((U|T)A(A|G|R))|((U|T)GA))",
    },
    36: {
        "A":  "(GC.)",
        "B":  "((A(U|T).)|(C(U|T)G)|(G(U|T)G)|((U|T)(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "(GG.)",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((CG(U|T|C|Y|A))|(AG(A|G|R)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((CGG)|((U|T)GG))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "(((U|T)A(A|G|R))|((U|T)GA))",
        "_":  "(((U|T)A(A|G|R))|((U|T)GA))",
    },
    37: {
        "A":  "(GC.)",
        "B":  "((A(U|T).)|(C(U|T)G)|(G(U|T)G)|((U|T)(U|T)G))",
        "C":  "((U|T)G(U|T|C|Y))",
        "D":  "(GA(U|T|C|Y))",
        "E":  "(GA(A|G|R))",
        "F":  "((U|T)(U|T)(U|T|C|Y))",
        "G":  "((GG.)|((U|T)GA))",
        "H":  "(CA(U|T|C|Y))",
        "I":  "(A(U|T)(U|T|C|Y|A))",
        "K":  "(AA(A|G|R))",
        "L":  "((C(U|T).)|((U|T)(U|T)(A|G|R)))",
        "M":  "(A(U|T)G)",
        "N":  "(AA(U|T|C|Y))",
        "P":  "(CC.)",
        "Q":  "(CA(A|G|R))",
        "R":  "((AG(A|G|R))|(CG(U|T|C|Y)))",
        "S":  "(((U|T)C.)|(AG(U|T|C|Y)))",
        "T":  "(AC.)",
        "V":  "(G(U|T).)",
        "W":  "((CG(A|G|R))|((U|T)GG))",
        "X":  "...",
        "Y":  "((U|T)A(U|T|C|Y))",
        "*":  "((U|T)A(A|G|R))",
        "_":  "((U|T)A(A|G|R))",
    },
}


def compile_table(codontable: int) -> dict[str, re.Pattern[str]]:
    """Compile one genetic code's patterns, anchored to a whole codon."""
    try:
        table = P2C[codontable]
    except KeyError:
        raise ValueError(f"unsupported codon table: {codontable}") from None
    return {aa: re.compile(pat + r"\Z") for aa, pat in table.items()}
